[book]
authors = ["forgetest contributors"]
language = "en"
multilingual = false
src = "src"
title = "forgetest Documentation"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/MysterionRise/forgetest"
